{% set name = "gipl" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/permamodel/GIPL-BMI-Fortran/archive/v{{ version }}.tar.gz
  sha256: 1368359e92b5fb7cccbe6181911ddf0e50364e28430e563d0bf2d2bc1026116e

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - make
    - cmake

test:
  source_files:
    - data
  commands:
    - run_bmigipl_model data/gipl_config.cfg

about:
  home: https://csdms.colorado.edu/wiki/Model:GIPL
  license: MIT
  license_file: LICENSE
  summary: "A numerical model of soil properties in polar regions."
  description: |
    The Geophysical Institute Permafrost Laboratory (GIPL) model uses
    the effect of snow layers and subsurface soil thermal properties
    to simulate ground temperatures and active layer thickness by
    numerically solving the 1D heat diffusion equation with phase
    change using finite-differnce techniques. This version of the GIPL
    model includes a Basic Model Interface (BMI) created by Kang Wang
    (university of Colorado Boulder).
  doc_url: https://csdms.colorado.edu/wiki/Model_help:GIPL
  dev_url: https://github.com/permamodel/GIPL_BMI_Fortran

extra:
  recipe-maintainers:
    - mdpiper
