{% set name = "gipl" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/permamodel/GIPL-BMI-Fortran/archive/v{{ version }}.tar.gz
  sha256: 40665117705804057eaa3be4f17033904c080b3b419cb6f9824863b4ffc22c67

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}  # [win]
    - {{ stdlib("c") }}
    - make  # [unix]
    - cmake

test:
  source_files:
    - data
  commands:
    - run_bmigipl_model --help
    - run_bmigipl_model data/gipl_config.cfg

about:
  home: https://csdms.colorado.edu/wiki/Model:GIPL
  license: MIT
  license_file: LICENSE
  summary: "A numerical model of soil properties in polar regions."
  description: |
    The Geophysical Institute Permafrost Laboratory (GIPL) model uses
    the effect of snow layers and subsurface soil thermal properties
    to simulate ground temperatures and active layer thickness by
    numerically solving the 1D heat diffusion equation with phase
    change using finite-differnce techniques. This version of the GIPL
    model includes a Basic Model Interface (BMI) created by Kang Wang
    (university of Colorado Boulder).
  doc_url: https://csdms.colorado.edu/wiki/Model_help:GIPL
  dev_url: https://github.com/permamodel/GIPL_BMI_Fortran

extra:
  recipe-maintainers:
    - mdpiper
