travis:
  secure:
    BINSTAR_TOKEN: FVu5GYCphX3LDRTHfCWQWnL1Skw7ChLTom8BKcqPmNKGmqQs9jaM0fSdd7kTU2m5C8iMNLAiP4hki0VXxROGLtmO2ctEOwc6S49RPU5uLE7630HSuQimxNw2Ex9XweBLCMCFEcK+vL+rFjZHkvdH5xR6oPFV0uI49Z6OW9KgP73gXgFqHq6XzZw/Ptbs5n4oY5Wc/QdLgdmKkJ5IdM8/qBrRyTwnhxehLShvgMwFvtl0UX4Rhi2DrUsr5Z/ZwKZ0PCZ5V7MChn4UhUlRr0ja9+V+wv50BQ+v/xj3gzIJiMweRHaYB37vL26rGywNuBUCGkXsMr2wpI7gy5Vkyhtx44rQThXc50FqBRlNDqNTU/FQjMeiE0OYApcdEDNxLRj+z1tK2YrTBC1bi36GeqX52yJ8ExcnNZqcs7sbFxJ2djSJ/oOU9SMDj39kAFGKWZIV3FQT14GaM5pM/inrKvYcl0qcAtT08KEyWiDEIuv3jeZGN/biCl/xGf9v6LoY5+8TrqfWlyIwoTwl/tZWvOhQE4UWX2XfFwnOsqurDxCa7bj4tcclliBsX4mtCGJvV1RyJpPipYrW+CZWRcn4pcKViN1S3aTdmcS2bhHgPHQO9+h72EinUmC2lUPD517r67rpuxBBkZFZcldGeULJz652PdwBRXyqBkw1tliZsRTo8Q4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
